#!/bin/bash
if [ "$#" -ne 1 ]; then
	echo "Illegal number of parameters"
	echo "Usage: delete_pebble_project.sh <project_name>"
	exit 1
fi
export PEBBLE_PROJECTS_ROOT=$HOME/.pbl/projects
export PEBBLE_PROJECT_NAME=$1
if [ ! -d "$PEBBLE_PROJECTS_ROOT/$PEBBLE_PROJECT_NAME" ]; then
	echo "Project directory does not exist! This likely means the project does not exist. Run pebble/new_pebble_project to create the container and project directory."
	exit 1
elif [ ! "$(docker ps -a | grep $PEBBLE_PROJECT_NAME)" ]; then
	echo "Container does not exist! This likely means the container does not exist. Run pebble/new_pebble_project to create the container and project directory."
else
	docker stop $PEBBLE_PROJECT_NAME
	docker rm $PEBBLE_PROJECT_NAME
fi
read -p "THIS IS THE POINT OF NO RETURN! Are you sure you want to delete \"$PEBBLE_PROJECTS_ROOT/$PEBBLE_PROJECT_NAME\"? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	echo "Here goes nothing! Deleting \"$PEBBLE_PROJECTS_ROOT/$PEBBLE_PROJECT_NAME\""
	rm -rf $PEBBLE_PROJECTS_ROOT/$PEBBLE_PROJECT_NAME
	echo "Finished deleting \"$PEBBLE_PROJECTS_ROOT/$PEBBLE_PROJECT_NAME\""
	echo ""
	echo "If you want to create a new project, run pebble/new_pebble_project"
else
	echo "Halt! Aborting deletion of \"$PEBBLE_PROJECTS_ROOT/$PEBBLE_PROJECT_NAME\"" 
	echo ""
	echo "Exiting..."
	exit 1
fi
unset PEBBLE_PROJECTS_ROOT
unset PEBBLE_PROJECT_NAME
